# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  labels:
    name: web-app
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-app-pod
      app: website

  template:
    metadata:
      name: web-app-pod
      labels:
         name: web-app-pod
         app: website
    spec:
      containers:
        - name: web-app
          image: ugoeze/web-app:1.0
          ports:
            - containerPort: 80
      imagePullSecrets: 
        - name: dockerhub-user

---
#service

apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    name: web-app-service
    app: website
spec:
  selector:
    name: web-app-pod
    app: website
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80

