
---
kind: Service
apiVersion: v1
metadata:
  name: http2-with-cert-minimal
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http2"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "6fafcc1a36f1edf17edcb17d253b8a9566111a9a" 
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http2
      protocol: TCP
      port: 443
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
